### ISSUE TITLE
win binary pls?

### ISSUE THREAD

**Issue by necros2k7** [snapcrafters/opentyrian#5]
subj

**Comment by lucyllewy** [comment]
Can you expand on the question, because it isn't clear what you're asking for...

**Comment by necros2k7** [comment]
can you upload compiled windows build to Releases tab?

**Comment by lucyllewy** [comment]
This repository is for a Snap package of OpenTyrian. Snaps are Linux-specific; you cannot run snaps on Windows so we're not building any Windows binaries.

**Comment by lucyllewy** [comment]
You can [download OpenTyrian for Windows at the project page](https://bitbucket.org/opentyrian/opentyrian/downloads/). Because this ask is out of scope for the Snap packaging I'm closing the issue.
